name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'jeremy-4wbqqfav'
  PROJECT_NMR: 157769428517
  REGION: 'europe-west1'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          workload_identity_provider: 'projects/${{env.PROJECT_NMR}}/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
          service_account: 'github-wif@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
          project_id: ${{env.PROJECT_ID}}

      - name: Copy file to bucket
        run: |-
          gsutil cp ./src/* gs://${{env.PROJECT_ID}}-static-content/

