name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'jeremy-4wbqqfav'
  PROJECT_NMR: 157769428517
  REGION: 'europe-west1'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - id: 'Checkout'
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{env.PROJECT_NMR}}/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
          service_account: 'github-wif@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
          project_id: ${{env.PROJECT_ID}}

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './src'
          service_account: 'cloudstorage-sa@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
          destination: '${{env.PROJECT_ID}}-static-content'
